# Generated by Django 5.0.6 on 2024-05-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
