# Generated by Django 5.0.4 on 2024-05-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_profile_created_on_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_on',
        ),
    ]
