# Generated by Django 3.2.8 on 2024-05-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
